[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# SPA fallback so client-side routes work on refresh
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
<<<<<<< HEAD

=======
>>>>>>> b3e8d8dc333e98714227c1a5482ed43ac9c5ab19
